# Generated by Django 3.1 on 2020-10-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='middletName',
            new_name='middleName',
        ),
    ]
